/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComparativaRouteImport } from './routes/comparativa'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as AlumnosIndexRouteImport } from './routes/alumnos.index'
import { Route as AlumnosIdRouteImport } from './routes/alumnos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativaRoute = ComparativaRouteImport.update({
  id: '/comparativa',
  path: '/comparativa',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnosIndexRoute = AlumnosIndexRouteImport.update({
  id: '/alumnos/',
  path: '/alumnos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnosIdRoute = AlumnosIdRouteImport.update({
  id: '/alumnos/$id',
  path: '/alumnos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comparativa': typeof ComparativaRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/alumnos/$id': typeof AlumnosIdRoute
  '/alumnos/': typeof AlumnosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comparativa': typeof ComparativaRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/alumnos/$id': typeof AlumnosIdRoute
  '/alumnos': typeof AlumnosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comparativa': typeof ComparativaRoute
  '/cursos': typeof CursosRoute
  '/dashboard': typeof DashboardRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/alumnos/$id': typeof AlumnosIdRoute
  '/alumnos/': typeof AlumnosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comparativa'
    | '/cursos'
    | '/dashboard'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/alumnos/$id'
    | '/alumnos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comparativa'
    | '/cursos'
    | '/dashboard'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/alumnos/$id'
    | '/alumnos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comparativa'
    | '/cursos'
    | '/dashboard'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/alumnos/$id'
    | '/alumnos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComparativaRoute: typeof ComparativaRoute
  CursosRoute: typeof CursosRoute
  DashboardRoute: typeof DashboardRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  ReportesRoute: typeof ReportesRoute
  AlumnosIdRoute: typeof AlumnosIdRoute
  AlumnosIndexRoute: typeof AlumnosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativa': {
      id: '/comparativa'
      path: '/comparativa'
      fullPath: '/comparativa'
      preLoaderRoute: typeof ComparativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnos/': {
      id: '/alumnos/'
      path: '/alumnos'
      fullPath: '/alumnos/'
      preLoaderRoute: typeof AlumnosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnos/$id': {
      id: '/alumnos/$id'
      path: '/alumnos/$id'
      fullPath: '/alumnos/$id'
      preLoaderRoute: typeof AlumnosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComparativaRoute: ComparativaRoute,
  CursosRoute: CursosRoute,
  DashboardRoute: DashboardRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  ReportesRoute: ReportesRoute,
  AlumnosIdRoute: AlumnosIdRoute,
  AlumnosIndexRoute: AlumnosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
